# Kubernetes Secret resource for secure storage of sensitive configuration data
# Version: v1
# Security: AES-256 encryption, automated rotation, audit logging
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: porfin-system
  labels:
    app: porfin
    environment: ${ENV}
    managed-by: terraform
    rotation-schedule: 30d
  annotations:
    # Enable envelope encryption using Google Cloud KMS
    encryption.kubernetes.io/key: ${KMS_KEY_ID}
    # Enable audit logging for all secret access
    audit.kubernetes.io/enabled: "true"
    # Enable encryption for backups
    backup.kubernetes.io/encryption: "enabled"

# Opaque type for arbitrary secret data
type: Opaque

# Base64 encoded secret values
# Note: Values are templated and injected by Terraform/deployment pipeline
data:
  # Main application secret key for session/token signing
  SECRET_KEY: ${BASE64_SECRET_KEY}
  
  # Firebase service account credentials for authentication
  FIREBASE_CREDENTIALS: ${BASE64_FIREBASE_CREDENTIALS}
  
  # OpenAI API key for GPT-4 integration
  OPENAI_API_KEY: ${BASE64_OPENAI_API_KEY}
  
  # WhatsApp Business API credentials
  WHATSAPP_API_TOKEN: ${BASE64_WHATSAPP_API_TOKEN}
  
  # Google Calendar API service account credentials
  GOOGLE_CALENDAR_CREDENTIALS: ${BASE64_GOOGLE_CALENDAR_CREDENTIALS}
  
  # Redis password for cache access
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}