# Service Accounts configuration for Porfin application components
# Version: v1.25+
# Purpose: Defines service accounts with enhanced security controls and IAM integration

---
# Backend Service Account with enhanced security controls
apiVersion: v1
kind: ServiceAccount
metadata:
  name: porfin-backend
  namespace: porfin-system
  labels:
    app: porfin
    component: backend
    environment: ${ENV}
    managed-by: kustomize
    security-tier: restricted
  annotations:
    # Security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    iam.gke.io/gcp-service-account: porfin-backend@${PROJECT_ID}.iam.gserviceaccount.com
    security.porfin.io/token-rotation: "enabled"
    security.porfin.io/audit-logging: "enabled"
    security.porfin.io/secret-mount-policy: "explicit"
    
    # Compliance annotations
    security.compliance/data-classification: restricted
    security.compliance/lgpd-compliant: "true"
    
    # Monitoring configuration
    monitoring.porfin.io/audit-events: "true"
    monitoring.porfin.io/token-expiry-alert: "24h"
automountServiceAccountToken: true
secrets:
  - name: app-secrets
  - name: gcp-credentials

---
# Frontend Service Account with minimal permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: porfin-frontend
  namespace: porfin-system
  labels:
    app: porfin
    component: frontend
    environment: ${ENV}
    managed-by: kustomize
    security-tier: standard
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    iam.gke.io/gcp-service-account: porfin-frontend@${PROJECT_ID}.iam.gserviceaccount.com
    security.porfin.io/token-rotation: "enabled"
    security.porfin.io/audit-logging: "enabled"
    security.porfin.io/secret-mount-policy: "explicit"
    
    # Compliance annotations
    security.compliance/data-classification: standard
    security.compliance/lgpd-compliant: "true"
automountServiceAccountToken: true
secrets:
  - name: frontend-secrets

---
# AI Service Account for machine learning workloads
apiVersion: v1
kind: ServiceAccount
metadata:
  name: porfin-ai
  namespace: porfin-system
  labels:
    app: porfin
    component: ai
    environment: ${ENV}
    managed-by: kustomize
    security-tier: restricted
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    iam.gke.io/gcp-service-account: porfin-ai@${PROJECT_ID}.iam.gserviceaccount.com
    security.porfin.io/token-rotation: "enabled"
    security.porfin.io/audit-logging: "enabled"
    security.porfin.io/secret-mount-policy: "explicit"
    
    # AI-specific security controls
    security.porfin.io/ml-model-validation: "enabled"
    security.compliance/data-classification: restricted
    security.compliance/lgpd-compliant: "true"
automountServiceAccountToken: true
secrets:
  - name: ai-secrets
  - name: gcp-credentials
  - name: model-credentials

---
# WhatsApp Integration Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: porfin-whatsapp
  namespace: porfin-system
  labels:
    app: porfin
    component: whatsapp
    environment: ${ENV}
    managed-by: kustomize
    security-tier: restricted
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    iam.gke.io/gcp-service-account: porfin-whatsapp@${PROJECT_ID}.iam.gserviceaccount.com
    security.porfin.io/token-rotation: "enabled"
    security.porfin.io/audit-logging: "enabled"
    security.porfin.io/secret-mount-policy: "explicit"
    
    # WhatsApp-specific security controls
    security.porfin.io/message-encryption: "enabled"
    security.compliance/data-classification: restricted
    security.compliance/lgpd-compliant: "true"
automountServiceAccountToken: true
secrets:
  - name: whatsapp-secrets
  - name: gcp-credentials