apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: porfin-system
  labels:
    app: porfin
    component: monitoring
    service: prometheus
    version: v1
    tier: observability
data:
  prometheus.yml: |
    # Global configuration
    global:
      scrape_interval: 15s     # Default scrape interval for all jobs
      evaluation_interval: 15s  # Interval for evaluating rules
      scrape_timeout: 10s      # Timeout for scrape requests
      external_labels:
        environment: production
        cluster: porfin-main
        region: brazil
        product: porfin

    # Rule files for alerting and recording rules
    rule_files:
      - /etc/prometheus/rules/recording.rules
      - /etc/prometheus/rules/alerting.rules
      - /etc/prometheus/rules/security.rules

    # Scrape configurations
    scrape_configs:
      # Kubernetes API server monitoring
      - job_name: kubernetes-apiservers
        honor_labels: true
        scheme: https
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
                - kube-system
                - porfin-system
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      # Porfin API monitoring
      - job_name: porfin-api
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: porfin
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_component]
            regex: api
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8000"
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'go_.*'
            action: drop

      # WhatsApp service monitoring
      - job_name: porfin-whatsapp
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        scrape_interval: 10s  # More frequent for critical service
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_service]
            regex: whatsapp
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: porfin
            action: keep

      # AI service monitoring
      - job_name: porfin-ai
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_component]
            regex: ai
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: porfin
            action: keep

      # Node monitoring
      - job_name: kubernetes-nodes
        scheme: https
        kubernetes_sd_configs:
          - role: node
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Security metrics monitoring
      - job_name: security-metrics
        honor_timestamps: true
        metrics_path: /metrics
        scheme: https
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_security_monitoring]
            regex: "true"
            action: keep

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - porfin-system
          scheme: http
          timeout: 10s
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: alertmanager
              action: keep
            - source_labels: [__meta_kubernetes_pod_container_port_number]
              regex: "9093"
              action: keep

    # Storage configuration
    storage:
      tsdb:
        retention:
          time: 15d
          size: 50GB
        wal:
          retention:
            time: 12h