# Kubernetes Service configuration for Prometheus monitoring server
# Version: v1
# Purpose: Exposes Prometheus metrics collection and querying endpoints within the cluster

apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: porfin-system
  labels:
    app: porfin
    component: monitoring
    service: prometheus
    # Additional labels for service discovery and monitoring
    version: v1
    tier: monitoring
    managed-by: kubernetes

spec:
  # Using ClusterIP for internal cluster access only
  type: ClusterIP
  
  # Port configuration for Prometheus server
  ports:
    - port: 9090  # Standard Prometheus port
      targetPort: 9090
      protocol: TCP
      name: http  # Named port for easier reference
  
  # Selector matches labels from Prometheus deployment
  selector:
    app: porfin
    component: monitoring
    service: prometheus

  # Additional service specifications for production readiness
  sessionAffinity: None  # No session affinity needed for metrics
  publishNotReadyAddresses: false  # Only expose ready pods
  
  # Internal traffic policy for optimized routing
  internalTrafficPolicy: Cluster