version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    resources:
      limits:
        memory: 512M
        cpus: '1'
      reservations:
        memory: 256M
        cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    init: true
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: web_net
      com.docker.network.bridge.enable_icc: 'true'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/volumes/web_node_modules/_data
      o: bind

x-config:
  name: web-docker-compose
  version: 1.0.0
  maintainers:
    - DevOps Team
  labels:
    environment: development
    application: porfin-web
    version: 1.0.0